export default {
  REGISTER: '/api/register',
  LOGIN: '/api/login',
  GETUSERNAME: '/api/getUserName',
  POST: '/api/post',
  LOGOUT: '/api/logout',
  GETSOMEONEPOSTS: '/api/getSomeOnePosts',
  GETALLPOSTS: '/api/getAllPosts',
  GETARTICLE: '/api/getArticle',
  POSTIMAGE: '/api/postImage',
  DOWNIMAGE: '/api/downImage',
  POSTCOMMENT: '/api/postComment',
  GETCOMMENT: '/api/getComment',
  PRAISECOMMENT: '/api/praiseComment',
  REPLAYCOMMENT: '/api/replayComment',
};
